### ISSUE TITLE
您好大佬,我用了您写的areaCode,我有一个问题想问您

### ISSUE THREAD

**Issue by wuzhuohan7788** [yeshu-cn/AreaCodeSample#1]
我在使用您写的控件中,在使用这个单击事件的时候
`ac_Adapter.setItemClickListener(new SimpleRecyclerViewAdapter.OnItemClickListener<AreaCodeItem>() {
            @Override
            public void onItemClick(int position, AreaCodeItem item) {
                Toast.makeText(AreaCodeActivity.this, position, Toast.LENGTH_LONG).show();
            }
        });`,总是会报 Resources$NotFoundException,我想请问一下,这个单击事件的具体用法,我想获取item中的值

**Comment by yeshu-cn** [comment]
> 我在使用您写的控件中,在使用这个单击事件的时候
> `ac_Adapter.setItemClickListener(new SimpleRecyclerViewAdapter.OnItemClickListener<AreaCodeItem>() { @Override public void onItemClick(int position, AreaCodeItem item) { Toast.makeText(AreaCodeActivity.this, position, Toast.LENGTH_LONG).show(); } });`,总是会报 Resources$NotFoundException,我想请问一下,这个单击事件的具体用法,我想获取item中的值

你报错因为Toast第二个参数错误了：Toast.makeText(MainActivity.this, position, Toast.LENGTH_LONG).show();
改为：Toast.makeText(MainActivity.this, “” + position, Toast.LENGTH_LONG).show();
